### ISSUE TITLE
Worker stays in suspended state

### ISSUE THREAD

**Issue by danielkucera** [jenkinsci/docker-inbound-agent#172]
Jenkins master shows:
```
yw674-test-14-pfb9q-92hxs-r7m3n  (launching...)   (suspended)
```
pod logs:
```
# oc logs yw674-test-14-pfb9q-92hxs-r7m3n
May 18, 2020 6:20:17 PM hudson.remoting.jnlp.Main createEngine
INFO: Setting up agent: yw674-test-14-pfb9q-92hxs-r7m3n
May 18, 2020 6:20:17 PM hudson.remoting.jnlp.Main$CuiListener <init>
INFO: Jenkins agent is running in headless mode.
May 18, 2020 6:20:17 PM hudson.remoting.Engine startEngine
INFO: Using Remoting version: 4.3
May 18, 2020 6:20:17 PM org.jenkinsci.remoting.engine.WorkDirManager initializeWorkDir
INFO: Using /home/jenkins/agent/remoting as a remoting work directory
May 18, 2020 6:20:17 PM org.jenkinsci.remoting.engine.WorkDirManager setupLogging
INFO: Both error and output logs will be printed to /home/jenkins/agent/remoting
May 18, 2020 6:20:18 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: WebSocket connection open
May 18, 2020 6:20:19 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connected
```
pod description
```
# oc describe pods
Name:         yw674-test-14-pfb9q-92hxs-rnb3s
Namespace:    jenkins
Priority:     0
Node:         master1/192.168.99.100
Start Time:   Mon, 18 May 2020 20:22:13 +0200
Labels:       jenkins=slave
              jenkins/label=yw674-test_14-pfb9q
Annotations:  buildUrl: https://***HOST***/job/yw674-test/14/
              k8s.v1.cni.cncf.io/networks-status:
                [{
                    "name": "openshift-sdn",
                    "interface": "eth0",
                    "ips": [
                        "10.129.0.248"
                    ],
                    "dns": {},
                    "default-route": [
                        "10.129.0.1"
                    ]
                }]
              openshift.io/scc: restricted
              runUrl: job/yw674-test/14/
Status:       Running
IP:           10.129.0.248
IPs:
  IP:  10.129.0.248
Containers:
  jnlp:
    Container ID:   cri-o://56c314376b33e7702d9942bf90e2066753b8587eb02eeafa0583e193c7b231c3
    Image:          ***.io/jenkins/jnlp-slave:4.3-4
    Image ID:       ***.io/jenkins/jnlp-slave@sha256:f77d8309471861a08de71471fc145e2559e685db9724905af8de66a09405f5fc
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Mon, 18 May 2020 20:22:16 +0200
    Ready:          True
    Restart Count:  0
    Environment:
      JENKINS_SECRET:         74260a7928128a921732c06f3ef75dc5076173ce7bec63898e6a5f0ab5cad397
      JENKINS_AGENT_NAME:     yw674-test-14-pfb9q-92hxs-rnb3s
      JENKINS_WEB_SOCKET:     true
      JENKINS_NAME:           yw674-test-14-pfb9q-92hxs-rnb3s
      JENKINS_AGENT_WORKDIR:  /home/jenkins/agent
      JENKINS_URL:            https://***.de/
    Mounts:
      /home/jenkins/agent from workspace-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-rpzjc (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  workspace-volume:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  default-token-rpzjc:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-rpzjc
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  beta.kubernetes.io/os=linux
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age        From               Message
  ----    ------     ----       ----               -------
  Normal  Scheduled  <invalid>  default-scheduler  Successfully assigned jenkins/yw674-test-14-pfb9q-92hxs-rnb3s to master1
  Normal  Pulled     <invalid>  kubelet, master1   Container image "***.io/jenkins/jnlp-slave:4.3-4" already present on machine
  Normal  Created    <invalid>  kubelet, master1   Created container jnlp
  Normal  Started    <invalid>  kubelet, master1   Started container jnlp
```

**Comment by michaelkuty** [comment]
Same for us, working only with `jenkins/jnlp-slave:4.0.1-1` without any issues, when we use inbound in 4.3 jnlp says connected but we get this

``
Error in provisioning; agent=KubernetesSlave name: jenkins-job-builder-324-7spjt-wjlg8, template=PodTemplate{inheritFrom='template', name='jenkins-job-builder-324-7spjt', namespace='jenkins', hostNetwork=false, label='jenkins-job-builder-324', nodeSelector='', nodeUsageMode=EXCLUSIVE, workspaceVolume=EmptyDirWorkspaceVolume [memory=false], containers=[ContainerTemplate{name='jnlp', image='jenkins/inbound-agent:latest', ttyEnabled=true}], annotations=[org.csanchez.jenkins.plugins.kubernetes.PodAnnotation@aab9c821, org.csanchez.jenkins.plugins.kubernetes.PodAnnotation@c92c82e4], imagePullSecrets=[org.csanchez.jenkins.plugins.kubernetes.PodImagePullSecret@40ba07e2]}
java.lang.IllegalStateException: Agent is not connected after 100 seconds, status: Running
	at org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher.launch(KubernetesLauncher.java:202)
	at hudson.slaves.SlaveComputer.lambda$_connect$0(SlaveComputer.java:292)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
``

**Comment by danielkucera** [comment]
I've got it working. The problem was caused by missing `ttyEnabled: true` in container template:
```
        containerTemplate(
            name: 'ubuntu', 
            image: 'ubuntu:latest',
            ttyEnabled: true
            ),
```
