### ISSUE TITLE
ERROR: Error cloning remote repo 'origin'

### ISSUE THREAD

**Issue by ryan4yin** [jenkinsci/docker-inbound-agent#175]
after upgrade docker image from `jenkins/jnlp-slave:4.0.1-1` to `jenkins/inbound-agent:4.3-4`, the `git` plugin failed with the following error:

```
...
[Pipeline] git
using credential git-ssh-privatekey
Cloning the remote Git repository
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Command "git fetch --tags --force --progress -- http://gitlab.xxx.local/Front/function/xxx.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
stdout: 
stderr: jenkins@gitlab.xxx.local: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2430)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:2044)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$500(CliGitAPIImpl.java:81)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:569)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:798)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:161)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:154)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:117)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 192.168.1.107/192.168.1.107:60724
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1788)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
		at hudson.remoting.Channel.call(Channel.java:998)
		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:146)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:132)
		at com.sun.proxy.$Proxy88.execute(Unknown Source)
		at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1122)
		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1167)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:125)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:93)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:80)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		... 1 more
```

pipeline:

```
git branch: env.BRANCH, credentialId: "git-ssh-privatekey", url: "http://gitlab.xxx.local/Front/function/xxx.git"
```

upgrade jenkins master's image `jenkins/jenkins:lts` didn't work.

switch back to the old version `jenkins/jnlp-slave:4.0.1-1`  solved the error.

Avoiding the use of git plug-ins can also solve this problem:

```
sshagent (credentials: ['git-ssh-privatekey']) {
    sh "git clone -b ${env.BRANCH} http://gitlab.xxx.local/Front/function/xxx.git"
}
```

**Comment by slide** [comment]
@MarkEWaite any ideas on this?

**Comment by nexaddo** [comment]
I'm also having the same issue

**Comment by MarkEWaite** [comment]
@nexaddo the message indicates an incorrect credential or repository URL is being used.

```
Cloning the remote Git repository
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Command "git fetch --tags --force --progress -- http://gitlab.xxx.local/Front/function/xxx.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
stdout: 
stderr: jenkins@gitlab.xxx.local: Permission denied (publickey).
fatal: Could not read from remote repository.
```

The repository URL is an HTTP URL but the "permission denied" message is for a public key.  Public key authentication is used by git for ssh based repositories.  The repository URL in that exception is an HTTP URL.  Username / password authentication must be used for HTTP and HTTPS repository URLs.

**Comment by ryancurrah** [comment]
I am also seeing the same problem, the same creds work with the older agent.

**Comment by slide** [comment]
It uses the same URL on the older agent image with a public key?

**Comment by ryan4yin** [comment]
> @nexaddo the message indicates an incorrect credential or repository URL is being used.
> 
> ```
> Cloning the remote Git repository
> ERROR: Error cloning remote repo 'origin'
> hudson.plugins.git.GitException: Command "git fetch --tags --force --progress -- http://gitlab.xxx.local/Front/function/xxx.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
> stdout: 
> stderr: jenkins@gitlab.xxx.local: Permission denied (publickey).
> fatal: Could not read from remote repository.
> ```
> 
> The repository URL is an HTTP URL but the "permission denied" message is for a public key. Public key authentication is used by git for ssh based repositories. The repository URL in that exception is an HTTP URL. Username / password authentication must be used for HTTP and HTTPS repository URLs.

I make a custom image based on `jenkins/jnlp-slave:4.0.1-1`, which add the command below:

```dockerfile
RUN git config --global url."git@gitlab.svc.local:".insteadOf "https://gitlab.svc.local"
```

this caused git use `ssh` instead of `http`.

**Comment by Manoj21333** [comment]
> C:\Program Files\Git\bin init C:\ProgramData\Jenkins\.jenkins\workspace\dockerProject # timeout=10
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Could not init C:\ProgramData\Jenkins\.jenkins\workspace\dockerProject
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$5.execute(CliGitAPIImpl.java:1042)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:797)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1226)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1308)
	at hudson.scm.SCM.checkout(SCM.java:540)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1217)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:647)
	 what would be the problem

**Comment by MarkEWaite** [comment]
It could be a permissions issue with the file system. It could be that the git.exe program is not in the path.  It could be many things.

The issue tracker is used to track issues.  Your request seems to be a request for help.

Please use the [mailing lists](https://www.jenkins.io/mailing-lists/) and the [chat channels](https://www.jenkins.io/chat/) for questions.
