### ISSUE TITLE
included agent.jar in jenkins/inbound-agent:jdk8 requires newer java

### ISSUE THREAD

**Issue by cfraenkel** [jenkinsci/docker-inbound-agent#276]
### Jenkins and plugins versions report

jenkins/inbound-agent:jdk8 with Digest: sha256:c746ffa4eb0744efb1b1422e32a7f6c0ec078b4cd94c8f58c735da93ef95a7c6

### What Operating System are you using (both controller, and any agents involved in the problem)?

docker on linux x64

### Reproduction steps

Run the docker image, either standalone or e.g. via kubernetes plugin. 
```
docker pull jenkins/inbound-agent:jdk8
docker run --rm  jenkins/inbound-agent:jdk8
```

### Expected Results

Agent starts up

### Actual Results

agent directly fails with `java.lang.UnsupportedClassVersionError`
```
docker run --rm  jenkins/inbound-agent:jdk8
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: hudson/remoting/jnlp/Main has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)
```

### Anything else?

The docker image was not modified. It still worked on 2022-09-03 so I suspect it broke with the push done for #274

**Comment by timja** [comment]
Best to use a specific version and not rely on latest, this was accidental because JDK 8 is no longer supported in new Jenkins versions and we will get it sorted.

**Comment by cfraenkel** [comment]
the image that was pushed 4 days ago (08. Sept) seems to work again:
https://hub.docker.com/layers/jenkins/inbound-agent/jdk8/images/sha256-f9f2fc969070f6690e670afc2a2ae5c79ac64ff36c516bcc9f6fcfea021139c2?context=explore
```
docker  pull jenkins/inbound-agent:jdk8
jdk8: Pulling from jenkins/inbound-agent
1671565cc8df: Already exists
539f7fd75221: Pull complete
83fce082dea0: Pull complete
9a1ba8efd544: Pull complete
7c20503f1bce: Pull complete
2dee96827809: Pull complete
4f4fb700ef54: Pull complete
5df66cf67c90: Pull complete
da3ecca8e1af: Pull complete
Digest: sha256:f9f2fc969070f6690e670afc2a2ae5c79ac64ff36c516bcc9f6fcfea021139c2
Status: Downloaded newer image for jenkins/inbound-agent:jdk8
docker.io/jenkins/inbound-agent:jdk8

 docker run  --rm  jenkins/inbound-agent:jdk8
two arguments required, but got []
java -jar agent.jar [options...] <secret key> <agent name>
 -agentLog FILE                        : Local agent error log destination
                                         (overrides workDir)
 -cert VAL                             : Specify additional X.509 encoded PEM
...
```
