### ISSUE TITLE
Container jnlp was terminated (Exit Code: 1, Reason: Error)

### ISSUE THREAD

**Issue by kkavin** [jenkinsci/docker-inbound-agent#307]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Kubernetes Worker nodes with Amazon linux 

with agents:
- jenkins/inbound-agent:alpine
- jenkins/inbound-agent:latest

### Reproduction steps

Step -1 : Created pipeline  with the yaml configuration 
containers:
      - name: jnlp
        image: jenkins/inbound-agent:alpine
        securityContext:
            runAsUser: 1001
            runAsUser: 1001
Step -2 : Running the pipline

### Expected Results

Jnlp image creation successful

### Actual Results

Pipeline failed with the below error 

**Container jnlp was terminated (Exit Code: 1, Reason: Error)
 jnlp -- terminated (1)
Error: Could not find or load main class hudson.remoting.jnlp.Main

Caused by: java.lang.ClassNotFoundException: hudson.remoting.jnlp.Main**

### Anything else?

After updating to this new image all the pipelines are getting failed

**Comment by peterwvj** [comment]
We are experiencing this issue too with inbound-agent:latest. We have downgraded inbound-agent to version 4.10-3-jdk11 to avoid this problem.

**Comment by timja** [comment]
could you attach a full log please?

I would also recommend you don't use the latest tag and instead use a specific version. e.g. `3077.vd69cf116da_6f-1`

**Comment by kkavin** [comment]
We have tried different version and getting the same issue

Please find the logs below

**Pipeline logs:**

16:25:43  [Pipeline] Start of Pipeline
16:25:43  [Pipeline] podTemplate
16:25:43  [Pipeline] {
16:25:43  [Pipeline] node
16:25:53  Created Pod: kubernetes jenkins/test-jenkins-15-s5m9r-gz6zc-bgvq9
16:25:55  jenkins/test-jenkins-15-s5m9r-gz6zc-bgvq9 Container jnlp was terminated (Exit Code: 1, Reason: Error)
16:25:55  
16:25:55  - jnlp -- terminated (1)
16:25:55  -----Logs-------------
16:25:55  Error: Could not find or load main class hudson.remoting.jnlp.Main
16:25:55  Caused by: java.lang.ClassNotFoundException: hudson.remoting.jnlp.Main
16:25:55  
16:25:55  
16:25:55  - maven -- running
16:25:55  -----Logs-------------
16:25:55  
16:25:55  [Pipeline] // node
16:25:55  [Pipeline] }
16:25:55  [Pipeline] // podTemplate
16:25:55  [Pipeline] End of Pipeline
16:25:55  Queue task was cancelled
16:25:55  Finished: ABORTED



**Jenkins logs:**
2022-11-22 06:34:34.424+0000 [id=683]	INFO	o.c.j.p.k.KubernetesSlave#_terminate: Terminating Kubernetes instance for agent alm-env-manger-qa-60582-9tqfc-rgj2v-xtx8v
2022-11-22 06:34:34.434+0000 [id=683]	SEVERE	o.c.j.p.k.KubernetesSlave#_terminate: Computer for agent is null: alm-env-manger-qa-60582-9tqfc-rgj2v-xtx8v
2022-11-22 06:34:34.434+0000 [id=683]	INFO	hudson.slaves.AbstractCloudSlave#terminate: FATAL: Computer for agent is null: alm-env-manger-qa-60582-9tqfc-rgj2v-xtx8v
2022-11-22 06:35:37.540+0000 [id=1437]	INFO	hudson.model.AsyncPeriodicWork#lambda$doRun$1: Started DockerContainerWatchdog Asynchronous Periodic Work
2022-11-22 06:35:37.541+0000 [id=1437]	INFO	c.n.j.p.d.DockerContainerWatchdog#execute: Docker Container Watchdog has been triggered
2022-11-22 06:35:37.541+0000 [id=1437]	INFO	c.n.j.p.d.DockerContainerWatchdog$Statistics#writeStatisticsToLog: Watchdog Statistics: Number of overall executions: 5, Executions with processing timeout: 0, Containers removed gracefully: 0, Containers removed with force: 0, Containers removal failed: 0, Nodes removed successfully: 0, Nodes removal failed: 0, Container removal average duration (gracefully): 0 ms, Container removal average duration (force): 0 ms, Average overall runtime of watchdog: 0 ms, Average runtime of container retrieval: 0 ms
2022-11-22 06:35:37.541+0000 [id=1437]	INFO	c.n.j.p.d.DockerContainerWatchdog#loadNodeMap: We currently have 0 nodes assigned to this Jenkins instance, which we will check
2022-11-22 06:35:37.541+0000 [id=1437]	INFO	c.n.j.p.d.DockerContainerWatchdog#execute: Docker Container Watchdog check has been completed
2022-11-22 06:35:37.541+0000 [id=1437]	INFO	hudson.model.AsyncPeriodicWork#lambda$doRun$1: Finished DockerContainerWatchdog Asynchronous Periodic Work. 0 ms
2022-11-22 06:36:04.295+0000 [id=1478]	INFO	hudson.slaves.NodeProvisioner#update: alm-env-manger-qa-60591-4wkpm-hl1rp-wc1h2 provisioning successfully completed. We have now 2 computer(s)
2022-11-22 06:36:04.314+0000 [id=1479]	INFO	o.c.j.p.k.KubernetesLauncher#launch: Created Pod: kubernetes jenkins/alm-env-manger-qa-60591-4wkpm-hl1rp-wc1h2
2022-11-22 06:36:06.053+0000 [id=385]	INFO	o.c.j.p.k.p.r.Reaper$TerminateAgentOnContainerTerminated#lambda$onEvent$1: jenkins/alm-env-manger-qa-60591-4wkpm-hl1rp-wc1h2 Container jnlp was just terminated, so removing the corresponding Jenkins agent
2022-11-22 06:36:06.069+0000 [id=385]	INFO	o.c.j.p.k.KubernetesSlave#_terminate: Terminating Kubernetes instance for agent alm-env-manger-qa-60591-4wkpm-hl1rp-wc1h2
2022-11-22 06:36:06.079+0000 [id=385]	INFO	o.c.j.p.k.KubernetesSlave#deleteSlavePod: Terminated Kubernetes instance for agent jenkins/alm-env-manger-qa-60591-4wkpm-hl1rp-wc1h2
2022-11-22 06:36:06.080+0000 [id=385]	INFO	o.c.j.p.k.KubernetesSlave#_terminate: Disconnected computer alm-env-manger-qa-60591-4wkpm-hl1rp-wc1h2
2022-11-22 06:36:44.429+0000 [id=771]	WARNING	o.c.j.p.k.KubernetesLauncher#launch: Error in provisioning; agent=KubernetesSlave name: alm-env-manger-qa-60583-6x8fp-hszkr-8s7s6, template=PodTemplate{id='6337741b-4a35-4914-b949-8f8ea419a281', name='ALM_ENV_MANGER_QA_60583-6x8fp-hszkr', label='ALM_ENV_MANGER_QA_60583-6x8fp', annotations=[PodAnnotation{key='buildUrl', value='http://jenkins.jenkins.svc.cluster.local:80/job/ALM_ENV_MANGER_QA/60583/'}, PodAnnotation{key='runUrl', value='job/ALM_ENV_MANGER_QA/60583/'}]}
io.fabric8.kubernetes.client.KubernetesClientTimeoutException: Timed out waiting for [1000000] milliseconds for [Pod] with name:[alm-env-manger-qa-60583-6x8fp-hszkr-8s7s6] in namespace [jenkins].
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.waitUntilCondition(BaseOperation.java:860)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.waitUntilReady(BaseOperation.java:842)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.waitUntilReady(BaseOperation.java:83)
	at org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher.launch(KubernetesLauncher.java:173)
	at hudson.slaves.SlaveComputer.lambda$_connect$0(SlaveComputer.java:298)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:48)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:82)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2022-11-22 06:36:44.430+0000 [id=771]	INFO	o.c.j.p.k.KubernetesSlave#_terminate: Terminating Kubernetes instance for agent alm-env-manger-qa-60583-6x8fp-hszkr-8s7s6
2022-11-22 06:36:44.438+0000 [id=771]	SEVERE	o.c.j.p.k.KubernetesSlave#_terminate: Computer for agent is null: alm-env-manger-qa-60583-6x8fp-hszkr-8s7s6
2022-11-22 06:36:44.438+0000 [id=771]	INFO	hudson.slaves.AbstractCloudSlave#terminate: FATAL: Computer for agent is null: alm-env-manger-qa-60583-6x8fp-hszkr-8s7s6
2022-11-22 06:37:53.268+0000 [id=1566]	INFO	hudson.model.AsyncPeriodicWork#lambda$doRun$1: Started Bundle Upload
2022-11-22 06:37:54.297+0000 [id=1563]	INFO	hudson.slaves.NodeProvisioner#update: alm-env-manger-qa-60592-80w73-8v8h9-w66bq provisioning successfully completed. We have now 2 computer(s)
2022-11-22 06:37:54.312+0000 [id=1564]	INFO	o.c.j.p.k.KubernetesLauncher#launch: Created Pod: kubernetes jenkins/alm-env-manger-qa-60592-80w73-8v8h9-w66bq
2022-11-22 06:37:56.058+0000 [id=385]	INFO	o.c.j.p.k.p.r.Reaper$TerminateAgentOnContainerTerminated#lambda$onEvent$1: jenkins/alm-env-manger-qa-60592-80w73-8v8h9-w66bq Container jnlp was just terminated, so removing the corresponding Jenkins agent
2022-11-22 06:37:56.075+0000 [id=385]	INFO	o.c.j.p.k.KubernetesSlave#_terminate: Terminating Kubernetes instance for agent alm-env-manger-qa-60592-80w73-8v8h9-w66bq
2022-11-22 06:37:56.085+0000 [id=385]	INFO	o.c.j.p.k.KubernetesSlave#deleteSlavePod: Terminated Kubernetes instance for agent jenkins/alm-env-manger-qa-60592-80w73-8v8h9-w66bq
2022-11-22 06:37:56.087+0000 [id=385]	INFO	o.c.j.p.k.KubernetesSlave#_terminate: Disconnected computer alm-env-manger-qa-60592-80w73-8v8h9-w66bq
2022-11-22 06:38:19.990+0000 [id=1566]	INFO	c.c.j.p.a.client.AdvisorClient#doUploadFile: Bundle successfully uploaded. Response code was: 200
2022-11-22 06:38:20.133+0000 [id=1566]	INFO	hudson.model.AsyncPeriodicWork#lambda$doRun$1: Finished Bundle Upload. 26,864 ms
2022-11-22 06:38:35.429+0000 [id=863]	WARNING	o.c.j.p.k.KubernetesLauncher#launch: Error in provisioning; agent=KubernetesSlave name: alm-env-manger-qa-60584-h6f9q-9rwp3-nc088, template=PodTemplate{id='c08229cc-d10c-42e6-9b9a-8b0ab8246eb7', name='ALM_ENV_MANGER_QA_60584-h6f9q-9rwp3', label='ALM_ENV_MANGER_QA_60584-h6f9q', annotations=[PodAnnotation{key='buildUrl', value='http://jenkins.jenkins.svc.cluster.local:80/job/ALM_ENV_MANGER_QA/60584/'}, PodAnnotation{key='runUrl', value='job/ALM_ENV_MANGER_QA/60584/'}]}
io.fabric8.kubernetes.client.KubernetesClientTimeoutException: Timed out waiting for [1000000] milliseconds for [Pod] with name:[alm-env-manger-qa-60584-h6f9q-9rwp3-nc088] in namespace [jenkins].
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.waitUntilCondition(BaseOperation.java:860)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.waitUntilReady(BaseOperation.java:842)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.waitUntilReady(BaseOperation.java:83)
	at org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher.launch(KubernetesLauncher.java:173)
	at hudson.slaves.SlaveComputer.lambda$_connect$0(SlaveComputer.java:298)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:48)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:82)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2022-11-22 06:38:35.429+0000 [id=863]	INFO	o.c.j.p.k.KubernetesSlave#_terminate: Terminating Kubernetes instance for agent alm-env-manger-qa-60584-h6f9q-9rwp3-nc088
2022-11-22 06:38:35.438+0000 [id=863]	SEVERE	o.c.j.p.k.KubernetesSlave#_terminate: Computer for agent is null: alm-env-manger-qa-60584-h6f9q-9rwp3-nc088
2022-11-22 06:38:35.439+0000 [id=863]	INFO	hudson.slaves.AbstractCloudSlave#terminate: FATAL: Computer for agent is null: alm-env-manger-qa-60584-h6f9q-9rwp3-nc088
2022-11-22 06:40:04.296+0000 [id=1655]	INFO	hudson.slaves.NodeProvisioner#update: alm-env-manger-qa-60593-wcp36-3059s-xsvvf provisioning successfully completed. We have now 2 computer(s)
2022-11-22 06:40:04.313+0000 [id=1656]	INFO	o.c.j.p.k.KubernetesLauncher#launch: Created Pod: kubernetes jenkins/alm-env-manger-qa-60593-wcp36-3059s-xsvvf
2022-11-22 06:40:06.044+0000 [id=385]	INFO	o.c.j.p.k.p.r.Reaper$TerminateAgentOnContainerTerminated#lambda$onEvent$1: jenkins/alm-env-manger-qa-60593-wcp36-3059s-xsvvf Container jnlp was just terminated, so removing the corresponding Jenkins agent
2022-11-22 06:40:06.061+0000 [id=385]	INFO	o.c.j.p.k.KubernetesSlave#_terminate: Terminating Kubernetes instance for agent alm-env-manger-qa-60593-wcp36-3059s-xsvvf
2022-11-22 06:40:06.075+0000 [id=385]	INFO	o.c.j.p.k.KubernetesSlave#deleteSlavePod: Terminated Kubernetes instance for agent jenkins/alm-env-manger-qa-60593-wcp36-3059s-xsvvf
2022-11-22 06:40:06.076+0000 [id=385]	INFO	o.c.j.p.k.KubernetesSlave#_terminate: Disconnected computer alm-env-manger-qa-60593-wcp36-3059s-xsvvf
2022-11-22 06:40:37.541+0000 [id=1669]	INFO	hudson.model.AsyncPeriodicWork#lambda$doRun$1: Started DockerContainerWatchdog Asynchronous Periodic Work
2022-11-22 06:40:37.541+0000 [id=1669]	INFO	c.n.j.p.d.DockerContainerWatchdog#execute: Docker Container Watchdog has been triggered
2022-11-22 06:40:37.541+0000 [id=1669]	INFO	c.n.j.p.d.DockerContainerWatchdog$Statistics#writeStatisticsToLog: Watchdog Statistics: Number of overall executions: 6, Executions with processing timeout: 0, Containers removed gracefully: 0, Containers removed with force: 0, Containers removal failed: 0, Nodes removed successfully: 0, Nodes removal failed: 0, Container removal average duration (gracefully): 0 ms, Container removal average duration (force): 0 ms, Average overall runtime of watchdog: 0 ms, Average runtime of container retrieval: 0 ms
2022-11-22 06:40:37.541+0000 [id=1669]	INFO	c.n.j.p.d.DockerContainerWatchdog#loadNodeMap: We currently have 0 nodes assigned to this Jenkins instance, which we will check
2022-11-22 06:40:37.541+0000 [id=1669]	INFO	c.n.j.p.d.DockerContainerWatchdog#execute: Docker Container Watchdog check has been completed
2022-11-22 06:40:37.541+0000 [id=1669]	INFO	hudson.model.AsyncPeriodicWork#lambda$doRun$1: Finished DockerContainerWatchdog Asynchronous Periodic Work. 0 ms
2022-11-22 06:40:44.425+0000 [id=952]	WARNING	o.c.j.p.k.KubernetesLauncher#launch: Error in provisioning; agent=KubernetesSlave name: alm-env-manger-qa-60585-vlfq1-rlh30-pw7s2, template=PodTemplate{id='51790a83-a156-4315-bbc0-62a562714ee2', name='ALM_ENV_MANGER_QA_60585-vlfq1-rlh30', label='ALM_ENV_MANGER_QA_60585-vlfq1', annotations=[PodAnnotation{key='buildUrl', value='http://jenkins.jenkins.svc.cluster.local:80/job/ALM_ENV_MANGER_QA/60585/'}, PodAnnotation{key='runUrl', value='job/ALM_ENV_MANGER_QA/60585/'}]}
io.fabric8.kubernetes.client.KubernetesClientTimeoutException: Timed out waiting for [1000000] milliseconds for [Pod] with name:[alm-env-manger-qa-60585-vlfq1-rlh30-pw7s2] in namespace [jenkins].
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.waitUntilCondition(BaseOperation.java:860)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.waitUntilReady(BaseOperation.java:842)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.waitUntilReady(BaseOperation.java:83)
	at org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher.launch(KubernetesLauncher.java:173)
	at hudson.slaves.SlaveComputer.lambda$_connect$0(SlaveComputer.java:298)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:48)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:82)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by dduportal** [comment]
- What is the version of the JDK on your controller? If it is JDK8, then can you try with `https://github.com/jenkinsci/docker-inbound-agent/releases/tag/3028.va_a_436db_35078-2-jdk8` ? (and plan to upgrade you controller to JDK11 as soon as posible)
- Can you try by setting the field "Command to run" to `/usr/local/bin/jenkins-agent` and "Arguments to pass to the command" to `` (empty) on your Pod template please?

**Comment by kkavin** [comment]
Hi @dduportal  
The java version of Jenkins is below and we have tried https://github.com/jenkinsci/docker-inbound-agent/releases/tag/3028.va_a_436db_35078-2-jdk8 but the pods are not created using this agent


root@jenkins-78399b5weq:/# java -version
openjdk version "11.0.16.1" 2022-08-12
OpenJDK Runtime Environment Temurin-11.0.16.1+1 (build 11.0.16.1+1)
OpenJDK 64-Bit Server VM Temurin-11.0.16.1+1 (build 11.0.16.1+1, mixed mode)

**Comment by dduportal** [comment]
@kkavin While I'm trying to reproduce the error with a local k3s cluster, could you retrieve the agent pod's logs and description?
In order to do so, you'll have to, temporarly, set the Pod Template "Retention" to "Always" in the Jenkins UI -> Manage Jenkins -> Manage Node -> Manage Clouds -> browse to the Kubernetes section -> expand the Pod templates options -> select the "Advanced" button of the pod template .
This "retention" setup ensures that Jenkins won't delete the pod once failed so you can easily access it, get its description and logs, but you'll have to delete pods manually after.

**Comment by peterwvj** [comment]
This is most likely a problem with clouds that use a more restrictive user model (such as OpenShift). One of my colleagues looked into this and found that the problem could be related to this change https://github.com/jenkinsci/docker-agent/blame/master/11/alpine/Dockerfile#L42 introduced quite recently. The problem has also been introduced for other Debian og Archlinux images.  ` chmod 644` after the `ADD` might fix this.

4.10-3-jdk11 (works):
```
$ ls -la /usr/share/jenkins/
total 1476
drwxr-xr-x  2 root root      38 Nov  7 20:15 .
drwxr-xr-x 45 root root    4096 Nov  7 20:15 ..
-rw-r--r--  1 root root 1507326 Nov  7 20:15 agent.jar
lrwxrwxrwx  1 root root      28 Nov  7 20:15 slave.jar -> /usr/share/jenkins/agent.jar
```
latest (not working):
```
$ ls -la /usr/share/jenkins/
total 1344
drwxr-xr-x  2 jenkins jenkins      38 Nov 20 16:20 .
drwxr-xr-x 44 root    root       4096 Nov 20 16:20 ..
-rw-------  1 jenkins jenkins 1368830 Nov 18 17:05 agent.jar
lrwxrwxrwx  1 root    root         28 Nov 20 16:20 slave.jar -> /usr/share/jenkins/agent.jar
```

**Comment by dduportal** [comment]
> This is most likely a problem with clouds that use a restrictive user model (such as OpenShift). One of my colleagues looked into this and found that the problem could be related to this change https://github.com/jenkinsci/docker-agent/blame/master/11/alpine/Dockerfile#L42 introduced quite recently. The problem has also been introduced for other Debian og Archlinux images. ` chmod 644` after the `ADD` might fix this.
> 
> 4.10-3-jdk11 (works):
> 
> ```
> $ ls -la /usr/share/jenkins/
> total 1476
> drwxr-xr-x  2 root root      38 Nov  7 20:15 .
> drwxr-xr-x 45 root root    4096 Nov  7 20:15 ..
> -rw-r--r--  1 root root 1507326 Nov  7 20:15 agent.jar
> lrwxrwxrwx  1 root root      28 Nov  7 20:15 slave.jar -> /usr/share/jenkins/agent.jar
> ```
> 
> latest (not working):
> 
> ```
> $ ls -la /usr/share/jenkins/
> total 1344
> drwxr-xr-x  2 jenkins jenkins      38 Nov 20 16:20 .
> drwxr-xr-x 44 root    root       4096 Nov 20 16:20 ..
> -rw-------  1 jenkins jenkins 1368830 Nov 18 17:05 agent.jar
> lrwxrwxrwx  1 root    root         28 Nov 20 16:20 slave.jar -> /usr/share/jenkins/agent.jar
> ```

Good catch, thanks! Gotta publish a fix today

**Comment by dduportal** [comment]
First step for fixing: https://github.com/jenkinsci/docker-agent/pull/333 (then, release of `docker-agent`, PR to update parent image here and release of `docker-inbound-agent`)

**Comment by dduportal** [comment]
Thanks @peterwvj @kkavin , can you retry with the latest image (https://github.com/jenkinsci/docker-inbound-agent/releases/tag/3077.vd69cf116da_6f-2) ?

**Comment by peterwvj** [comment]
@dduportal thanks for looking into this. I will try out the new image tomorrow when I'm back at work and get back to you.

**Comment by dduportal** [comment]
> jenkins/inbound-agent:alpine

@kkavin thanks for the feedback. Can you share with us the digests of the images? I can't see any differences between `jenkins/inbound-agent:alpine-jdk11` and `jenkins/inbound-agent:alpine` (same digest, same layers) but I never had them so pulled from scratch (which could differ from your setup where and older version could be present).

Their digest should be the same:

```shell
$ docker pull jenkins/inbound-agent:alpine               
alpine: Pulling from jenkins/inbound-agent
ca7dd9ec2225: Already exists 
bb9822f87bb1: Already exists 
1ec5de7441ae: Already exists 
da0dd61568d7: Already exists 
1b5946bf4ab8: Pull complete 
ae36e3c04603: Pull complete 
910ecf5df8fc: Pull complete 
438a880a5d43: Pull complete 
e46780d55c94: Pull complete 
4f4fb700ef54: Pull complete 
aa9b5a50e6c1: Pull complete 
8ddadee1da24: Pull complete 
Digest: sha256:bf476e43de493f0bc1bf2030cc4da53b387e984e5239a2b3898862b9733a5dc7
Status: Downloaded newer image for jenkins/inbound-agent:alpine
docker.io/jenkins/inbound-agent:alpine
$ docker pull jenkins/inbound-agent:alpine-jdk11
alpine-jdk11: Pulling from jenkins/inbound-agent
Digest: sha256:bf476e43de493f0bc1bf2030cc4da53b387e984e5239a2b3898862b9733a5dc7
Status: Downloaded newer image for jenkins/inbound-agent:alpine-jdk11
docker.io/jenkins/inbound-agent:alpine-jdk11
```

**Comment by peterwvj** [comment]
@dduportal 3077.vd69cf116da_6f-2 and latest now work for me. Thanks again.

**Comment by kkavin** [comment]
@dduportal After pulling the docker image the pipeline is working fine. Thanks for fixing the issue @dduportal 
@peterwvj  Thanks 
![image](https://user-images.githubusercontent.com/12288251/203923333-00102c4c-c20f-43b7-9b34-5dac7cf8e6c8.png)

**Comment by dduportal** [comment]
Closing the issue as confirmed by users. Thanks a lot
