### ISSUE TITLE
latest-jdk8 docker image has Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

### ISSUE THREAD

**Issue by bvn13** [jenkinsci/docker-inbound-agent#320]
### Jenkins and plugins versions report

Jenkins 2.375.1 as host

docker image jenkins/ssh-agent:latest-jdk8

```
[01/04/23 20:59:05] [SSH] Starting agent process: cd "~" && java  -jar remoting.jar -workDir ~ -jar-cache ~/remoting/jarCache
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: hudson/remoting/Launcher has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)
```

### What Operating System are you using (both controller, and any agents involved in the problem)?

docker images hosted on ubuntu 22

### Reproduction steps

connect jenkins agent from docker latest-jdk8 failed

### Expected Results

success

### Actual Results

error

**Comment by bvn13** [comment]
related to https://github.com/jenkinsci/docker-inbound-agent/issues/282

**Comment by bvn13** [comment]
latest-alpine-jdk8 fails too

```
SSHLauncher{host='jenkins-agent-jdk8-1', port=22, credentialsId='jenkins', jvmOptions='', javaPath='', prefixStartSlaveCmd='', suffixStartSlaveCmd='', launchTimeoutSeconds=60, maxNumRetries=10, retryWaitTime=15, sshHostKeyVerificationStrategy=hudson.plugins.sshslaves.verifiers.NonVerifyingKeyVerificationStrategy, tcpNoDelay=true, trackCredentials=true}
[01/04/23 21:10:27] [SSH] Opening SSH connection to jenkins-agent-jdk8-1:22.
[01/04/23 21:10:27] [SSH] WARNING: SSH Host Keys are not being verified. Man-in-the-middle attacks may be possible against this connection.
[01/04/23 21:10:27] [SSH] Authentication successful.
[01/04/23 21:10:27] [SSH] The remote user's environment is:
BASH=/bin/bash
BASHOPTS=checkwinsize:cmdhist:complete_fullquote:extquote:force_fignore:globasciiranges:hostcomplete:interactive_comments:progcomp:promptvars:sourcepath
BASH_ALIASES=()
BASH_ARGC=()
BASH_ARGV=()
BASH_CMDS=()
BASH_EXECUTION_STRING=set
BASH_LINENO=()
BASH_SOURCE=()
BASH_VERSINFO=([0]="5" [1]="0" [2]="17" [3]="1" [4]="release" [5]="x86_64-alpine-linux-musl")
BASH_VERSION='5.0.17(1)-release'
DIRSTACK=()
EUID=1000
GROUPS=()
HOME=/home/jenkins
HOSTNAME=1f7b63f20f5a
HOSTTYPE=x86_64
IFS=$' \t\n'
LOGNAME=jenkins
MACHTYPE=x86_64-alpine-linux-musl
MAIL=/var/mail/jenkins
OPTERR=1
OPTIND=1
OSTYPE=linux-musl
PATH=/bin:/usr/bin:/sbin:/usr/sbin
PPID=28
PS4='+ '
PWD=/home/jenkins
SHELL=/bin/bash
SHELLOPTS=braceexpand:hashall:interactive-comments
SHLVL=1
SSH_CLIENT='172.19.0.5 45872 22'
SSH_CONNECTION='172.19.0.5 45872 172.19.0.6 22'
TERM=dumb
UID=1000
USER=jenkins
_=bash
Checking Java version in the PATH
bash: java: command not found
Java is not in the PATH nor configured with the javaPath setting, Jenkins will try to guess where is Java, this guess will be removed in the future. :Launch agents via SSH
[01/04/23 21:10:27] [SSH] Checking java version of ~/jdk/bin/java
Couldn't figure out the Java version of ~/jdk/bin/java
bash: /home/jenkins/jdk/bin/java: No such file or directory

[01/04/23 21:10:27] [SSH] Checking java version of java
Couldn't figure out the Java version of java
bash: java: command not found

[01/04/23 21:10:27] [SSH] Checking java version of /usr/bin/java
Couldn't figure out the Java version of /usr/bin/java
bash: /usr/bin/java: No such file or directory

[01/04/23 21:10:27] [SSH] Checking java version of /usr/java/default/bin/java
Couldn't figure out the Java version of /usr/java/default/bin/java
bash: /usr/java/default/bin/java: No such file or directory

[01/04/23 21:10:27] [SSH] Checking java version of /usr/java/latest/bin/java
Couldn't figure out the Java version of /usr/java/latest/bin/java
bash: /usr/java/latest/bin/java: No such file or directory

[01/04/23 21:10:27] [SSH] Checking java version of /usr/local/bin/java
Couldn't figure out the Java version of /usr/local/bin/java
bash: /usr/local/bin/java: No such file or directory

[01/04/23 21:10:27] [SSH] Checking java version of /usr/local/java/bin/java
Couldn't figure out the Java version of /usr/local/java/bin/java
bash: /usr/local/java/bin/java: No such file or directory

java.io.IOException: Java not found on hudson.slaves.SlaveComputer@5fbdd13f. Install Java 8 or Java 11 on the Agent.
	at hudson.plugins.sshslaves.JavaVersionChecker.resolveJava(JavaVersionChecker.java:83)
	at hudson.plugins.sshslaves.SSHLauncher.lambda$launch$0(SSHLauncher.java:453)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
[01/04/23 21:10:27] Launch failed - cleaning up connection
[01/04/23 21:10:27] [SSH] Connection closed.
```

**Comment by bvn13** [comment]
4.2.0-jdk8 fails

```
SSHLauncher{host='jenkins-agent-jdk8-1', port=22, credentialsId='jenkins', jvmOptions='', javaPath='', prefixStartSlaveCmd='', suffixStartSlaveCmd='', launchTimeoutSeconds=60, maxNumRetries=10, retryWaitTime=15, sshHostKeyVerificationStrategy=hudson.plugins.sshslaves.verifiers.NonVerifyingKeyVerificationStrategy, tcpNoDelay=true, trackCredentials=true}
[01/04/23 21:14:21] [SSH] Opening SSH connection to jenkins-agent-jdk8-1:22.
[01/04/23 21:14:21] [SSH] WARNING: SSH Host Keys are not being verified. Man-in-the-middle attacks may be possible against this connection.
[01/04/23 21:14:22] [SSH] Authentication successful.
[01/04/23 21:14:22] [SSH] The remote user's environment is:
BASH=/bin/bash
BASHOPTS=checkwinsize:cmdhist:complete_fullquote:extquote:force_fignore:globasciiranges:hostcomplete:interactive_comments:progcomp:promptvars:sourcepath
BASH_ALIASES=()
BASH_ARGC=([0]="0")
BASH_ARGV=()
BASH_CMDS=()
BASH_EXECUTION_STRING=set
BASH_LINENO=()
BASH_SOURCE=()
BASH_VERSINFO=([0]="5" [1]="1" [2]="4" [3]="1" [4]="release" [5]="x86_64-pc-linux-gnu")
BASH_VERSION='5.1.4(1)-release'
DIRSTACK=()
EUID=1000
GROUPS=()
HOME=/home/jenkins
HOSTNAME=683cf437ddfd
HOSTTYPE=x86_64
IFS=$' \t\n'
JAVA_HOME=/opt/java/openjdk
JENKINS_AGENT_HOME=/home/jenkins
JENKINS_AGENT_SSH_PUBKEY='ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC5OZeITuIz0bDjwpsFHnI7zaqMjDIWD5lNwjdLlE+oxL3pXVLc1VbqjaTphE8+vsbrAoIkSFxJ6PxYCsiU+a7F40AEWAwcOvzG9Q1D3GGjWtFN4l7nH4knKxymL8TOyPVVUfdJeNyODvSd8Hp+8kJh2f+u/ZJnxdwt1MHeSi/pRhJOk1z8AiEPC6muOnZ/fFIsGoN3BPkpJrubElfMswTu/3W0oc51/CzuJi10ozJU5J5G1/ZN7y9cIhas6kQLaCzYnVa1MBIxJOY8voyFuzDkSMATOUrpXuIXDR+Zw0dFCqflWRPRMRe7PeugJOuMH8ydEGcVuJKYoufWL6UIUQxCTl8m8FUaXp5s9EIoXKw4C7RPgD3cTHvZiK+tVArSpiJ3IXB7ZCrfhx6YChCZvT8itjcrkSVR2umxlDVUociixVgOdOWwb2OcMLqUZsM+mgzV0S4Tgs1fkzvm4ls6cwUetQYuvvuDxh8QAeBh3hm6k/iyMI/1k53M55L87ne0wPEskHZkBRtbejwOKuKO8ft6Z3kFTn1toMK3du8l95FnaiKSuGvY3yZ5Qu5VAeYpJEbb3GfVsPFSyCn83CsxWimPTvBwCvfD5++QwUifM6MkthNx8QfCyjxSehcB7/oNF2NsjSkBPWjH172Ou0E7XUhMG8yAd9lUNAbR84Qn8ZuyEQ== bvn13@bvn13-workbook'
LOGNAME=jenkins
MACHTYPE=x86_64-pc-linux-gnu
MOTD_SHOWN=pam
OPTERR=1
OPTIND=1
OSTYPE=linux-gnu
PATH=/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PIPESTATUS=([0]="0")
PPID=67
PS4='+ '
PWD=/home/jenkins
SHELL=/bin/bash
SHELLOPTS=braceexpand:hashall:interactive-comments
SHLVL=1
SSH_CLIENT='172.19.0.5 45880 22'
SSH_CONNECTION='172.19.0.5 45880 172.19.0.6 22'
TERM=dumb
UID=1000
USER=jenkins
_=']'
Checking Java version in the PATH
openjdk version "1.8.0_302"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_302-b08)
OpenJDK 64-Bit Server VM (Temurin)(build 25.302-b08, mixed mode)
[01/04/23 21:14:22] [SSH] Checking java version of ~/jdk/bin/java
Couldn't figure out the Java version of ~/jdk/bin/java
bash: line 1: /home/jenkins/jdk/bin/java: No such file or directory

[01/04/23 21:14:22] [SSH] Checking java version of java
[01/04/23 21:14:22] [SSH] java -version returned 1.8.0_302.
[01/04/23 21:14:22] [SSH] Starting sftp client.
[01/04/23 21:14:22] [SSH] Copying latest remoting.jar...
Source agent hash is 778DAD42A65312A61B7AE281A5F31129. Installed agent hash is 778DAD42A65312A61B7AE281A5F31129
Verified agent jar. No update is necessary.
Expanded the channel window size to 4MB
[01/04/23 21:14:22] [SSH] Starting agent process: cd "~" && java  -jar remoting.jar -workDir ~ -jar-cache ~/remoting/jarCache
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: hudson/remoting/Launcher has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)
Agent JVM has terminated. Exit code=1
[01/04/23 21:14:22] Launch failed - cleaning up connection
[01/04/23 21:14:22] [SSH] Connection closed.
SSHLauncher{host='jenkins-agent-jdk8-1', port=22, credentialsId='jenkins', jvmOptions='', javaPath='', prefixStartSlaveCmd='', suffixStartSlaveCmd='', launchTimeoutSeconds=60, maxNumRetries=10, retryWaitTime=15, sshHostKeyVerificationStrategy=hudson.plugins.sshslaves.verifiers.NonVerifyingKeyVerificationStrategy, tcpNoDelay=true, trackCredentials=true}
[01/04/23 21:14:41] [SSH] Opening SSH connection to jenkins-agent-jdk8-1:22.
[01/04/23 21:14:42] [SSH] WARNING: SSH Host Keys are not being verified. Man-in-the-middle attacks may be possible against this connection.
[01/04/23 21:14:42] [SSH] Authentication successful.
[01/04/23 21:14:42] [SSH] The remote user's environment is:
BASH=/bin/bash
BASHOPTS=checkwinsize:cmdhist:complete_fullquote:extquote:force_fignore:globasciiranges:hostcomplete:interactive_comments:progcomp:promptvars:sourcepath
BASH_ALIASES=()
BASH_ARGC=([0]="0")
BASH_ARGV=()
BASH_CMDS=()
BASH_EXECUTION_STRING=set
BASH_LINENO=()
BASH_SOURCE=()
BASH_VERSINFO=([0]="5" [1]="1" [2]="4" [3]="1" [4]="release" [5]="x86_64-pc-linux-gnu")
BASH_VERSION='5.1.4(1)-release'
DIRSTACK=()
EUID=1000
GROUPS=()
HOME=/home/jenkins
HOSTNAME=683cf437ddfd
HOSTTYPE=x86_64
IFS=$' \t\n'
JAVA_HOME=/opt/java/openjdk
JENKINS_AGENT_HOME=/home/jenkins
JENKINS_AGENT_SSH_PUBKEY='ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC5OZeITuIz0bDjwpsFHnI7zaqMjDIWD5lNwjdLlE+oxL3pXVLc1VbqjaTphE8+vsbrAoIkSFxJ6PxYCsiU+a7F40AEWAwcOvzG9Q1D3GGjWtFN4l7nH4knKxymL8TOyPVVUfdJeNyODvSd8Hp+8kJh2f+u/ZJnxdwt1MHeSi/pRhJOk1z8AiEPC6muOnZ/fFIsGoN3BPkpJrubElfMswTu/3W0oc51/CzuJi10ozJU5J5G1/ZN7y9cIhas6kQLaCzYnVa1MBIxJOY8voyFuzDkSMATOUrpXuIXDR+Zw0dFCqflWRPRMRe7PeugJOuMH8ydEGcVuJKYoufWL6UIUQxCTl8m8FUaXp5s9EIoXKw4C7RPgD3cTHvZiK+tVArSpiJ3IXB7ZCrfhx6YChCZvT8itjcrkSVR2umxlDVUociixVgOdOWwb2OcMLqUZsM+mgzV0S4Tgs1fkzvm4ls6cwUetQYuvvuDxh8QAeBh3hm6k/iyMI/1k53M55L87ne0wPEskHZkBRtbejwOKuKO8ft6Z3kFTn1toMK3du8l95FnaiKSuGvY3yZ5Qu5VAeYpJEbb3GfVsPFSyCn83CsxWimPTvBwCvfD5++QwUifM6MkthNx8QfCyjxSehcB7/oNF2NsjSkBPWjH172Ou0E7XUhMG8yAd9lUNAbR84Qn8ZuyEQ== bvn13@bvn13-workbook'
LOGNAME=jenkins
MACHTYPE=x86_64-pc-linux-gnu
MOTD_SHOWN=pam
OPTERR=1
OPTIND=1
OSTYPE=linux-gnu
PATH=/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PIPESTATUS=([0]="0")
PPID=114
PS4='+ '
PWD=/home/jenkins
SHELL=/bin/bash
SHELLOPTS=braceexpand:hashall:interactive-comments
SHLVL=1
SSH_CLIENT='172.19.0.5 45882 22'
SSH_CONNECTION='172.19.0.5 45882 172.19.0.6 22'
TERM=dumb
UID=1000
USER=jenkins
_=']'
Checking Java version in the PATH
openjdk version "1.8.0_302"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_302-b08)
OpenJDK 64-Bit Server VM (Temurin)(build 25.302-b08, mixed mode)
[01/04/23 21:14:42] [SSH] Checking java version of ~/jdk/bin/java
Couldn't figure out the Java version of ~/jdk/bin/java
bash: line 1: /home/jenkins/jdk/bin/java: No such file or directory

[01/04/23 21:14:42] [SSH] Checking java version of java
[01/04/23 21:14:42] [SSH] java -version returned 1.8.0_302.
[01/04/23 21:14:42] [SSH] Starting sftp client.
[01/04/23 21:14:42] [SSH] Copying latest remoting.jar...
Source agent hash is 778DAD42A65312A61B7AE281A5F31129. Installed agent hash is 778DAD42A65312A61B7AE281A5F31129
Verified agent jar. No update is necessary.
Expanded the channel window size to 4MB
[01/04/23 21:14:42] [SSH] Starting agent process: cd "~" && java  -jar remoting.jar -workDir ~ -jar-cache ~/remoting/jarCache
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: hudson/remoting/Launcher has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)
Agent JVM has terminated. Exit code=1
[01/04/23 21:14:42] Launch failed - cleaning up connection
[01/04/23 21:14:42] [SSH] Connection closed.
```

**Comment by gounthar** [comment]
Thanks a lot for this detailed issue. 👍

**Comment by bvn13** [comment]
4.6.0-alpine-jdk8 - the same error

is there any working image?
is this related to main jenkins image or agent?

**Comment by gounthar** [comment]
Thanks a lot for this detailed issue. :+1:
The thing that bothers me is that you're supposed to use an agent with the same JDK version as the controller...
Your controller is running JDK11 or JDK17, and not JDK8 (it's a recent version that *HAS* to run JDK11+), so your agent is not supposed to run JDK8.

**Comment by bvn13** [comment]
@gounthar 

I'm a new user of Jenkins.

Is there a possibility to have JDK 17 and JDK 8 agents for one main Jankins (Controller?) both?

My docker-compose is:

```
version: '3.8'

networks:
  jenkins:
    external: true

services:

  jenkins:
    image: jenkins/jenkins:lts
    #build: ./build/jenkins/
    networks:
      - jenkins
    privileged: true
    user: root
    ports:
     - 9000:8080
     - 50000:50000
    container_name: jenkins
    volumes:
     - ./jenkins_home:/var/jenkins_home
     - /var/run/docker.sock:/var/run/docker.sock

  jenkins-agent-1:
    image: jenkins/ssh-agent:latest-jdk17
    container_name: jenkins-agent-1
    networks:
      - jenkins
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa ...


  jenkins-agent-2:
    image: jenkins/ssh-agent:latest-jdk17
    container_name: jenkins-agent-2
    networks:
      - jenkins
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa ...
    
  jenkins-agent-jdk8-1:
    image: jenkins/ssh-agent:4.5.1-alpine-jdk8
    container_name: jenkins-agent-jdk8-1
    networks:
      - jenkins
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa ...

```

**Comment by gounthar** [comment]
I'm a pretty new user of Jenkins too.
I don't think you can have any agent with a JDK version that is inferior to the controller JDK version.
So if your controller is running JDK11, you won't be able to get agents running with JDK8.
Same for JDK17 and 11...

But that does not mean you can't run older versions of the JDK for your jobs.
You definitely can.
You just have to install other JDK versions in your agent thanks to "Global Tools Configuration" in the "Manage Jenkins" page.

**Comment by bvn13** [comment]
@gounthar 
I have just set Adopt Open JDK 8 up. And it doesn't take any effect. I cannot find any information about how to apply JDK settings. What should I do?

**Comment by gounthar** [comment]
@bvn13 please have a look at https://www.youtube.com/watch?v=qx3XK82BZPk&ab_channel=CloudBeesTV

**Comment by bvn13** [comment]
@gounthar I faced different behavior using Adopt JDK (I have no Oracle account) in comparison with video tutorial.
When I used adoptjdk-plugin it didn't download it.
When I changed it to permanent link to tar.gz file (https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u292-b10/OpenJDK8U-debugimage_x64_linux_hotspot_8u292b10.tar.gz) it downloaded it but JAVA_HOME and java didn't changed to downloaded version.

Here is my pipeline
```
pipeline {
    agent { label 'agent-jdk8-1' }

    tools {
        jdk 'adopt-openjdk-8'
    }
    
    stages {
        stage('testing') {
            steps {
                sh '''
                  env | grep -e PATH -e JAVA_HOME
                  which java
                  java -version || java --version
                '''
            }
        }
    }
}
```

and here is the output
```
Started by user [bvn13](https://jenkins.your-hike.ru/user/bvn13)
[Pipeline] Start of Pipeline
[Pipeline] node
Running on [agent-jdk8-1](https://jenkins.your-hike.ru/manage/computer/agent-jdk8-1/) in /home/jenkins/~/~/workspace/check env
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Declarative: Tool Install)
[Pipeline] tool
Unpacking https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u292-b10/OpenJDK8U-debugimage_x64_linux_hotspot_8u292b10.tar.gz to /home/jenkins/~/~/tools/hudson.model.JDK/adopt-openjdk-8 on agent-jdk8-1
[Pipeline] envVarsForTool
[Pipeline] }
[Pipeline] // stage
[Pipeline] withEnv
[Pipeline] {
[Pipeline] stage
[Pipeline] { (testing)
[Pipeline] tool
[Pipeline] envVarsForTool
[Pipeline] withEnv
[Pipeline] {
[Pipeline] sh
+ grep -e PATH -e JAVA_HOME
+ env
PATH=/home/jenkins/~/~/tools/hudson.model.JDK/adopt-openjdk-8/bin:/home/jenkins/~/~/tools/hudson.model.JDK/adopt-openjdk-8/bin:/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
JAVA_HOME=/home/jenkins/~/~/tools/hudson.model.JDK/adopt-openjdk-8
+ which java
/opt/java/openjdk/bin/java
+ java -version
openjdk version "17.0.5" 2022-10-18
OpenJDK Runtime Environment Temurin-17.0.5+8 (build 17.0.5+8)
OpenJDK 64-Bit Server VM Temurin-17.0.5+8 (build 17.0.5+8, mixed mode)
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Finished: SUCCESS
```

**Comment by bvn13** [comment]
I am going to close this issue due to my fault with incompatible images of Controller and Agent.

**Comment by gounthar** [comment]
Thanks @bvn13 .
Don't give up.
The community will find a way to help.
Please open a topic on [Discourse](https://community.jenkins.io/).
