### ISSUE TITLE
git-lfs is missing

### ISSUE THREAD

**Issue by kleini** [jenkinsci/docker-inbound-agent#70]
I am using this image within a Kubernetes pod to control a slave as this is the default container for such Jenkins slaves.
Checking out some Git repository using Git LFS within a declarative pipeline fails due to missing git-lfs binary.

    [Pipeline] {
    [Pipeline] stage
    [Pipeline] { (Declarative: Checkout SCM)
    [Pipeline] checkout
    Cloning the remote Git repository
    Cloning with configured refspecs honoured and without tags
    Cloning repository git@git.something.tld:git-lfs-test.git
     > /usr/bin/git init /var/lib/jenkins/workspace/kins_git-lfs-test_jenkins-EHEFW2M6YTSZSXCQN2C55M5ZSQFEMFT5ZOBC23X4WFGL7NLBKIIQ # timeout=10
    Fetching upstream changes from git@git.something.tld:git-lfs-test.git
     > /usr/bin/git --version # timeout=10
    using GIT_SSH to set credentials Local private SSH key of the Jenkins master server
     > /usr/bin/git fetch --no-tags --progress git@git.something.tld:git-lfs-test.git +refs/heads/*:refs/remotes/origin/*
     > /usr/bin/git config remote.origin.url git@git.something.tld:git-lfs-test.git # timeout=10
     > /usr/bin/git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
     > /usr/bin/git config remote.origin.url git@git.something.tld:git-lfs-test.git # timeout=10
    Fetching without tags
    Fetching upstream changes from git@git.something.tld:git-lfs-test.git
    using GIT_SSH to set credentials Local private SSH key of the Jenkins master server
     > /usr/bin/git fetch --no-tags --progress git@git.something.tld:git-lfs-test.git +refs/heads/*:refs/remotes/origin/*
    Checking out Revision 4eabb26d3e524942d8dc7599236e796dfc45f8cc (jenkins)
    Enabling Git LFS pull
     > /usr/bin/git config core.sparsecheckout # timeout=10
     > /usr/bin/git checkout -f 4eabb26d3e524942d8dc7599236e796dfc45f8cc
     > /usr/bin/git config --get remote.origin.url # timeout=10
    using GIT_SSH to set credentials Local private SSH key of the Jenkins master server
     > /usr/bin/git lfs pull origin
    [Pipeline] }
    [Pipeline] // stage
    [Pipeline] }
    [Pipeline] // node
    [Pipeline] End of Pipeline
    hudson.plugins.git.GitException: Command "/usr/bin/git lfs pull origin" returned status code 1:
    stdout: 
    stderr: git: 'lfs' is not a git command. See 'git --help'.

    Did you mean this?
        log

        at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1996)
        at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1715)
        at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:72)
        at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$9.execute(CliGitAPIImpl.java:2307)
    Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to Slave2
            at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)
            at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
            at hudson.remoting.Channel.call(Channel.java:955)
            at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:146)
            at sun.reflect.GeneratedMethodAccessor573.invoke(Unknown Source)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:498)
            at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:132)
            at com.sun.proxy.$Proxy103.execute(Unknown Source)
            at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1210)
            at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:113)
            at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:85)
            at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:75)
            at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
            at hudson.security.ACL.impersonate(ACL.java:290)
            at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
            at java.util.concurrent.FutureTask.run(FutureTask.java:266)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    Caused: hudson.plugins.git.GitException: Could not checkout 4eabb26d3e524942d8dc7599236e796dfc45f8cc
        at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$9.execute(CliGitAPIImpl.java:2319)
        at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:153)
        at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:146)
        at hudson.remoting.UserRequest.perform(UserRequest.java:212)
        at hudson.remoting.UserRequest.perform(UserRequest.java:54)
        at hudson.remoting.Request$2.run(Request.java:369)
        at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
    Finished: FAILURE

**Comment by kleini** [comment]
I am not sure, whether this report is correct here or git-lfs should go into the https://github.com/jenkinsci/docker-slave image.

**Comment by oleg-nenashev** [comment]
It should rather go to  https://github.com/jenkinsci/docker-slave, but we probably should firstly agree that we bundle it. Commonly tools should be installed by extending the image, but maybe Git LFS module is a valid case since Git is bundled. Not sure tho

WDYT @carlossg @ndeloof ?

**Comment by ndeloof** [comment]
no opinion on this topic. parent `openjdk` image bundle git, which doesn't make much sense, so I can't see any logic to offer guidance for installing git-lfs or not.

**Comment by kleini** [comment]
I tried to work around this issue now by using a separate Docker image having Git with LFS support installed. My pipeline code looks like the following

                container('git-lfs') {
                    checkout scm
                }

Unfortunately the Jenkins checkout DSL step either does not run on the surrounding container or uses some modified PATH environment, where git-lfs is not part of the path. I still get the same exception as mentioned above.

**Comment by jeff-knurek** [comment]
@kleini `checkout scm` has an option for setting a LFS pull, `[$class: "GitLFSPull"]`, have you tried that with your workaround?

----
even if you do, I expect you might still run into the same problem I did _(with a slightly different use case)_:
https://issues.jenkins-ci.org/browse/JENKINS-46230?focusedCommentId=311081&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-311081

**Comment by kleini** [comment]
@jeff-knurek LFS pull is configured in the multibranch pipeline configuration. I get the same error as stated in my first comment. So I expect git to do a 'lfs pull origin' but git-lfs tool is not found although contained in the surrounding Docker container. I tested the Docker container by hand and there everything works. 'git-lfs' is contained in the same path as git itself:

    # which git
    /usr/bin/git
    # which git-lfs
    /usr/bin/git-lfs

Therefore the only possible answer, why this fails, is, that 'checkout scm' is running within the jnlp Docker container and not within the surrounded one. I am not sure, whether this makes sense.

**Comment by ndeloof** [comment]
https://issues.jenkins-ci.org/browse/JENKINS-30600

**Comment by kleini** [comment]
@ndeloof thank you very much. Will extend first the jenkins/jnlp-slave:alpine with git-lfs to solve my build issues and wait for some fix from your side.

**Comment by ndeloof** [comment]
[my PR](https://github.com/jenkinsci/git-client-plugin/pull/219) never has been accepted, so don't know what you mean by "from your side", but you might have to wait for a few :)

**Comment by kleini** [comment]
@ndeloof Jenkins stated to go the Kubernetes way. I tried to and failed when using Git LFS. This needs to be fixed somehow in Jenkins, Git plugin or used JNLP slaves. This is, what I will wait for, because it is unclear for me, how this should be fixed correctly in regard of https://jenkins.io/blog/2018/08/31/shifting-gears/.

**Comment by oleg-nenashev** [comment]
I still believe that custom images are the way to go in general.
@MarkEWaite what is your opinion about git-lfs popularity? Does it worth including it to the standard image?

**Comment by MarkEWaite** [comment]
I think that git lfs should be considered a standard component just as we consider git a standard component.  Too much hassle to add it after the fact.

**Comment by kleini** [comment]
Adding git-lfs afterwards is not a big deal. But I expect there multiple users to be out there, using Git LFS. Here is, how i solved adding git-lfs support to the image: https://gitlab.open-xchange.com/jenkins/jnlp-slave
Please advice whether and where I should open a pull request to get this into the upstream images. I think it would be best to add it to the https://github.com/jenkinsci/docker-slave image.

**Comment by kleini** [comment]
Created https://github.com/jenkinsci/docker-slave/pull/39 to get this fixed.

**Comment by lemeurherve** [comment]
`git-lfs` has been added to the docker-agent parent image in https://github.com/jenkinsci/docker-agent/pull/58.
